# Generated by Django 2.1.5 on 2020-07-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recojuegoss',
            name='Semanas',
            field=models.PositiveIntegerField(default=3, verbose_name='Numero semanas'),
        ),
        migrations.AddField(
            model_name='recopeluche',
            name='Semanas',
            field=models.PositiveIntegerField(default=3, verbose_name='Numero semanas'),
        ),
        migrations.AddField(
            model_name='recotablero',
            name='Semanas',
            field=models.PositiveIntegerField(default=3, verbose_name='Numero semanas'),
        ),
        migrations.AddField(
            model_name='recovarita',
            name='Semanas',
            field=models.PositiveIntegerField(default=3, verbose_name='Numero semanas'),
        ),
    ]
