# Generated by Django 2.1.5 on 2020-01-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('edad_cron_mes', models.IntegerField(verbose_name='Edad Cronologica Meses')),
                ('edad_eval_mes', models.IntegerField(verbose_name='Edad Evaluacion Meses')),
                ('puntuacion', models.FloatField(verbose_name='Edad Evaluacion Evaluacion')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=10, verbose_name='Sexo')),
                ('lateralidad', models.CharField(choices=[('Diestro', 'Diestro'), ('Zurdo', 'Zurdo')], default='Diestro', max_length=10, verbose_name='Lateralidad')),
                ('unidad_edu', models.TextField(max_length=200, verbose_name='Unidad Educativa')),
                ('nivel', models.TextField(max_length=200, verbose_name='Nivel')),
                ('ciudad', models.TextField(max_length=200, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
                'ordering': ['-id'],
            },
        ),
    ]
