# Generated by Django 2.1.5 on 2020-01-10 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('M52', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Abre una puerta:')),
                ('M53', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Ensarta 4 cuentas grandes:')),
                ('M54', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Pasa páginas de un libro:')),
                ('M55', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Sujeta el papel mientras dibuja:')),
                ('M56', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Dobla una hoja de papel por la mitad:')),
                ('M57', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Corta con tijeras:')),
                ('M58', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Dobla dos veces el papel:')),
                ('M59', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Abre un candado con llave:')),
                ('M60', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Hace una pelota arrugando papel:')),
                ('M61', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Hace un nudo:')),
                ('M62', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Se toca con el pulgar las yemas de los dedos de la mano:')),
                ('M66', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Mete anillas en un soporte:')),
                ('M67', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Saca la pastilla de la botella:')),
                ('M68', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Copia una línea vertical:')),
                ('M69', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Copia un círculo:')),
                ('M70', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Copia una cruz:')),
                ('M71', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Corta con tijeras siguiendo una línea:')),
                ('M72', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Copia las letras V, H, T:')),
                ('M73', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Copia un triangulo:')),
                ('M74', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Dibuja una persona (incluyendo 6 elementos):')),
                ('M75', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Copia un cuadrado:')),
                ('M76', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Copia palabras sencillas:')),
                ('M77', models.CharField(choices=[('Adquirido', 'Adquirido'), ('En proceso', 'En proceso'), ('No adquirido', 'No adquirido'), ('No aplica', 'No aplica')], default='Adquirido', max_length=20, verbose_name='Copia los números del 1 al 15:')),
            ],
            options={
                'verbose_name': 'evaluacion',
                'verbose_name_plural': 'evaluaciones',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad_cron_mes',
            field=models.PositiveIntegerField(verbose_name='Edad Cronologica Meses'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad_eval_mes',
            field=models.PositiveIntegerField(verbose_name='Edad Evaluacion Meses'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nivel',
            field=models.CharField(max_length=100, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='puntuacion',
            field=models.FloatField(verbose_name='Puntuacion'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='unidad_edu',
            field=models.CharField(max_length=100, verbose_name='Unidad Educativa'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='Estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante', verbose_name='Estudiante Evaluado'),
        ),
    ]
