# Generated by Django 2.1.5 on 2020-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_auto_20200109_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='puntuacionMF',
            field=models.FloatField(default=0.0, verbose_name='Puntuacion tipica motricidad fina '),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='puntuacionMP',
            field=models.FloatField(default=0.0, verbose_name='Puntuacion tipica motricidad perceptiva'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='puntuacion',
            field=models.FloatField(verbose_name='Total area Motora '),
        ),
    ]
