# Generated by Django 2.1.5 on 2020-01-10 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0002_auto_20200109_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peluche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=100, verbose_name='Tipo Acividad')),
                ('Tiempo', models.CharField(max_length=20, verbose_name='Tipo de Acividad')),
                ('Ayuda', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Necesita Ayuda')),
            ],
            options={
                'verbose_name': 'Actividad Peluche',
                'verbose_name_plural': 'Actividades Peluche',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de Sesion')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante', verbose_name='Estudiante Evaluado')),
            ],
            options={
                'verbose_name': 'sesion',
                'verbose_name_plural': 'sesiones',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='peluche',
            name='Sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.Sesion', verbose_name='Sesion de Intervencion'),
        ),
    ]
