# Generated by Django 2.1.5 on 2020-01-16 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegoColorear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel', models.CharField(max_length=100, verbose_name='Nivel')),
                ('Tiem_Necesario', models.PositiveIntegerField(verbose_name='Tiempo Jugado')),
                ('Colores', models.CharField(max_length=100, verbose_name='Colores Usados')),
                ('Sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.Sesion', verbose_name='Sesion de Intervencion')),
            ],
            options={
                'verbose_name': 'Actividad Colorear',
                'verbose_name_plural': 'Actividades Colorear',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JuegoLaberinto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel', models.CharField(max_length=100, verbose_name='Nivel')),
                ('Tiem_Necesario', models.PositiveIntegerField(verbose_name='Tiempo Necesario')),
                ('Tiem_Logrado', models.PositiveIntegerField(verbose_name='Tiempo Logrado')),
                ('Intentos', models.PositiveIntegerField(verbose_name='Numero de Intentos')),
                ('Sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.Sesion', verbose_name='Sesion de Intervencion')),
            ],
            options={
                'verbose_name': 'Actividad Laberinto',
                'verbose_name_plural': 'Actividades Laberinto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JuegoLetras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel', models.CharField(max_length=100, verbose_name='Nivel')),
                ('Tiem_Necesario', models.PositiveIntegerField(verbose_name='Tiempo Necesario')),
                ('Tiem_Logrado', models.PositiveIntegerField(verbose_name='Tiempo Logrado')),
                ('Intentos', models.PositiveIntegerField(verbose_name='Numero de Intentos')),
                ('Sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.Sesion', verbose_name='Sesion de Intervencion')),
            ],
            options={
                'verbose_name': 'Actividad Laberinto',
                'verbose_name_plural': 'Actividades Laberinto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JuegoRompeC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel', models.CharField(max_length=100, verbose_name='Nivel')),
                ('Tiem_Necesario', models.PositiveIntegerField(verbose_name='Tiempo Necesario')),
                ('Tiem_Logrado', models.PositiveIntegerField(verbose_name='Tiempo Logrado')),
                ('Precision', models.CharField(max_length=100, verbose_name='Precision')),
                ('Num_Piezas', models.PositiveIntegerField(verbose_name='Numero de Piezas')),
                ('Sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.Sesion', verbose_name='Sesion de Intervencion')),
            ],
            options={
                'verbose_name': 'Actividad Juego Rompecabezas',
                'verbose_name_plural': 'Actividades Juego Rompecabezas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JuegoTopos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel', models.CharField(max_length=100, verbose_name='Nivel')),
                ('Cant_Agujeros', models.PositiveIntegerField(verbose_name='Cantidad Agujeros')),
                ('Tiem_Juego', models.PositiveIntegerField(verbose_name='Tiempo de Juego')),
                ('Tiem_Arriba', models.PositiveIntegerField(verbose_name='Tiempo topos superficie')),
                ('Tiem_Salida', models.PositiveIntegerField(verbose_name='Tiempo de salida de Topos')),
                ('Porce_Gana', models.PositiveIntegerField(verbose_name='Porcentaje necesario')),
                ('Num_Aciertos', models.PositiveIntegerField(verbose_name='Numero de Aciertos')),
                ('Num_Perdidos', models.PositiveIntegerField(verbose_name='Numero de Perdidos')),
                ('Num_Errores', models.PositiveIntegerField(verbose_name='Numero de Errores')),
                ('Porce_Logrado', models.PositiveIntegerField(verbose_name='Porcentaje Logrado')),
                ('Sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.Sesion', verbose_name='Sesion de Intervencion')),
            ],
            options={
                'verbose_name': 'Actividad Juego Topos',
                'verbose_name_plural': 'Actividades Juego Topos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Varita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel', models.CharField(max_length=100, verbose_name='Tipo Acividad')),
                ('Tiempo', models.CharField(max_length=20, verbose_name='Tiempo de Acividad')),
                ('Intentos', models.PositiveIntegerField(verbose_name='Numero de Intentos')),
                ('Sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.Sesion', verbose_name='Sesion de Intervencion')),
            ],
            options={
                'verbose_name': 'Actividad Varita',
                'verbose_name_plural': 'Actividades Varita',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='peluche',
            name='Tiempo',
            field=models.CharField(max_length=20, verbose_name='Tiempo de Acividad'),
        ),
    ]
