# Generated by Django 2.1.5 on 2020-01-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0002_auto_20200116_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peluche',
            name='Ayuda',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Necesita Ayuda'),
        ),
    ]
