# Generated by Django 2.1.5 on 2020-01-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0003_auto_20200124_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peluche',
            name='Ayuda',
            field=models.CharField(max_length=2, verbose_name='Necesita Ayuda'),
        ),
    ]
