# Generated by Django 2.1.5 on 2020-05-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0005_auto_20200124_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juegoletras',
            options={'ordering': ['-id'], 'verbose_name': 'Actividad Letra', 'verbose_name_plural': 'Actividades Letras'},
        ),
        migrations.AlterField(
            model_name='sesion',
            name='Estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante', verbose_name='Estudiante'),
        ),
    ]
