# Generated by Django 2.1.5 on 2020-07-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0006_auto_20200526_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Actividad', models.CharField(max_length=100, verbose_name='Tipo Acividad')),
                ('Tiempo', models.CharField(max_length=20, verbose_name='Tiempo de Acividad')),
                ('Errores', models.PositiveIntegerField(verbose_name='Numero de Errores')),
                ('Sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.Sesion', verbose_name='Sesion de Intervencion')),
            ],
            options={
                'verbose_name': 'Actividad Tablero',
                'verbose_name_plural': 'Actividades Tablero',
                'ordering': ['-id'],
            },
        ),
    ]
