# Generated by Django 2.1.5 on 2020-08-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0008_sesion_herramienta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='Herramienta',
            field=models.CharField(choices=[('Peluche MoFi', 'Peluche MoFi'), ('Juegos Serios', 'Juegos Serios'), ('Tablero Mofi', 'Tablero Mofi'), ('Tablero MoPe', 'Tablero MoPe'), ('Varita', 'Varita')], default='Peluche MoFi', max_length=60, verbose_name='Herramienta usada'),
        ),
    ]
