# Generated by Django 2.1.5 on 2020-08-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0009_auto_20200803_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegocolorear',
            name='Tiem_Necesario',
            field=models.CharField(max_length=100, verbose_name='Tiempo Jugado'),
        ),
    ]
