# Generated by Django 2.1.5 on 2020-05-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=160, verbose_name='Titulo')),
                ('Descripcion', models.TextField(verbose_name='Descripción')),
                ('Enlace', models.CharField(max_length=500, verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'contenido',
                'verbose_name_plural': 'contenidos',
                'ordering': ['-Titulo'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=160, verbose_name='Titulo')),
                ('Resumen', models.TextField(verbose_name='Resumen')),
                ('Enlace', models.CharField(max_length=500, verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
                'ordering': ['-Titulo'],
            },
        ),
    ]
